name: Riverpod flutter tests
on:
  pull_request:
    branches:
      - master
jobs:
  flutter_test:
    name: Run flutter tests and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v1.4.3
        with: 
          java-version: "12.x"
      - uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: "1.24.0-10.2.pre"
          channel: "beta"
      - name: Flutter tests
        working-directory: ./learn_riverpod
        run: |
          flutter pub get
          flutter analyze
          flutter test
